### ISSUE TITLE
IntelliJ Annotation processor prevents running tests in IntelliJ

### ISSUE THREAD

**Issue by drcrallen** [apache/incubator-druid#5849]
When I try to run tests from IntelliJ I'm getting the following error:

```
Error:java: Annotation processor 'io.druid.annotations.SubclassesMustBePublicAnnotationProcessor' not found
```

Running `mvn test` works fine.

**Comment by jihoonson** [comment]
Interesting. I've never met this error before.

**Comment by gianm** [comment]
I haven't hit it either. I am using IDEA 2018.1.

I think @clintropolis has hit something similar though.

**Comment by leventov** [comment]
I started to have this recently, too. Something broke in intellij.

**Comment by clintropolis** [comment]
My crummy workaround for now is to delete `.idea/compiler.xml`, but haven't determined the cause.

**Comment by leventov** [comment]
https://youtrack.jetbrains.com/issue/IDEA-193368

**Comment by leventov** [comment]
Why would not we update the version of maven-compiler-plugin project-wide?

**Comment by leventov** [comment]
@himanshug your suggestion didn't help me, I still get this build error.

**Comment by leventov** [comment]
This issue is presumably already fixed in IntelliJ 2018.2 EAP: https://youtrack.jetbrains.com/issue/IDEA-188940

**Comment by josephglanville** [comment]
Tests run for me using IDEA Ultimate 2018.2 EAP from Toolbox.

**Comment by himanshug** [comment]
@leventov 
> Why would not we update the version of maven-compiler-plugin project-wide?
if version upgrade fixed the problem then we would update in the common place unless there was a problem , why maintain different version in different poms unless necessary.

but anyways, it version update doesn't fix it so not necessary but I'm curious how it works with 3.2 when that configuration didn't exist there.

**Comment by drcrallen** [comment]
Confirmed fixed in the EAP

**Comment by leventov** [comment]
Closing this issue because IntelliJ 2018.2 with a fix is released

**Comment by asdf2014** [comment]
I also confirmed that after upgrading Intellij Idea to v2018.2, it no longer happens. Thanks all.
