### ISSUE TITLE
Reverse dependencies from /main/ to /test/

### ISSUE THREAD

**Issue by leerho** [apache/incubator-druid#6866]
Discussed in #6814

Druid-benchmarks has a number of reverse dependencies from the main tree back to the test-tree.  This is bad practice and should be corrected.  An even larger question is why is Druid-benchmarks even in the main tree? 

Specifically: 
```
druid-benchmarks
  org.apache.druid.benchmark
    ExpressionAggregationBenchmark
      import org.apache.druid.query.expression.TestExprMacroTable; //located in test tree
    ExpressionSelectorBenchmark
      import org.apache.druid.query.expression.TestExprMacroTable; //located in test tree
  org.apache.druid.benchmark.datagen
    SegmentGenerator
      import org.apache.druid.segment.IndexBuilder; //located in test tree
      import org.apache.druid.segment.TestHelper; //located in test tree
  //located in druid-processing-0.13.0-incubating-SNAPSHOT-tests.jar
  
  
  org.apache.druid.benchmark.query
    SqlBenchmark
      import org.apache.druid.sql.calcite.util.CalciteTests; //located in test tree
      import org.apache.druid.sql.calcite.util.SpecificSegmentsQuerySegmentWalker; //located in test tree
  //located in druid-sql-0.13.0-incubating-SNAPSHOT-tests.jar 
```

**Comment by gianm** [comment]
> An even larger question is why is Druid-benchmarks even in the main tree?

If I had to guess, it has something to do with that being the way whoever set it up got the packaging to work out for `benchmarks/target/benchmarks.jar`, which is where JMH benchmarks get run from. `druid-benchmarks` isn't part of the `distribution` package, so even though it has a main tree, that tree won't get distributed as part of a Druid binary package. (The kind you get from http://druid.apache.org/downloads.html)

If there's a way to move the sources to a test tree and still get `benchmarks/target/benchmarks.jar` to generate properly, then that would be more aesthetically appealing.

What should _not_ be done is moving some of that test stuff from other packages' `test` to `main`. That would pollute Druid binary packages.

**Comment by leerho** [comment]
Having `main` depending on `test` creates unnecessary errors, at least in Eclipse, I don't know how this is solved in IntelliJ.  And to fix those errors I have to manually copy and add the test jars into the build path, which is a PITA.  I don't think it is reasonable to expect all developers who wish to contribute to Druid to use IntelliJ. I not only have a huge history of projects in Eclipse, but I use it for C/C++, Ocaml, and other languages as well. 

In our DataSketches library we created a separate `characterization` repository, which is for long-running benchmarking tests and studies.  This makes the core repository clean. If `benchmarks` is not actually distributed,  might this work for Druid?

**Comment by leerho** [comment]
Then why not move benchmarks to test.  It would still have access to internal code. It would run only when specifically called, and not during unit test.

**Comment by leerho** [comment]
BTW, our reason for having this functionality separate from a release is to allow us to add new BM and continue to study and characterize performance after a release is out and run comparisons between releases. 

The task of characterization (and benchmarking) is never really done. We are constantly coming up with new and better ways to to this.

**Comment by gianm** [comment]
Moving benchmarks to test would be fine, so long as the `benchmarks/target/benchmarks.jar` still gets built properly (that's how people run the benchmarks).

**Comment by dampcake** [comment]
#7481 as it should fix this, and a few other issues that prevent druid from building with Eclipse.
@gianm If you have time can you take a look at it?
